languages:
  Ruby: false
  Javascript: false
  PHP: false
  Python: true

#
# ---Exclude Files or Directories---
# List the files or directories you would like excluded from analysis.
# For help setting your exclude paths:
# http://docs.codeclimate.com/article/166-excluding-files-folders
#
exclude_paths:
  - lexpy/tests/**