language: python
os:
  - linux
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install future
  - pip install coverage
  - pip install coveralls
script:
  - coverage run -m unittest discover -s lexpy/tests
  - coverage report -i -m
  - coveralls