env:
  global:
    - CC_TEST_REPORTER_ID=2f997b86dbf41562b2c965a189338cef075e7d96e0568d86f5cd7cce6d972065
language: python
os:
  - linux
python:
  - "2.7"
install:
  - pip install -r requirements.txt
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - coverage run -m unittest discover -s lexpy/tests
  - coverage report
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT